name: 'Get GitHub Project V2 Item IDs'
description: "This action outputs the ID of the items in your organization's GitHub Project."
branding:
  icon: 'layers'
  color: 'purple'

inputs:
  gh_token:
    description: 'GitHub Token with org permission'
    required: true
    default: ''
  org:
    description: "Your organization's name"
    required: false
    default: '' # defaults to github.context.repo.owner
  project_number:
    description: "Github Project's number in your organization"
    required: true
    default: ''
  repo:
    description: 'Repository name for filtering items'
    required: false
    default: ''
  single_select_field_id:
    description: 'Single select field ID for filtering items (single_select_field_option_id is required)'
    required: false
    default: ''
  single_select_field_option_id:
    description: 'Option ID of the supplied single select field for filtering items (single_select_field_id is required)'
    required: false
    default: ''
  label_name:
    description: 'Label name for filtering items'
    required: false
    default: ''

outputs:
  item_ids_json:
    description: 'filtered item ids in JSON'

runs:
  using: 'node16'
  main: 'dist/index.js'
